### ISSUE TITLE
[ /wines ] css 수정 및 와인 필터 모달 구현 1차

### ISSUE THREAD

**Issue by lemon1335** [Sprint-11-5team/WHYNE#133]
### 📝 간단하게 설명해주세요

> 전체적인 css수정은 거의 마무리 되었고, 필터쪽 디테일한 css 수정, 추천 와인 목록 버튼 위치 수정이 필요합니다.
필터모달 1차 구현은 된 상태인 것 같은데, 아직 확인은 못했습니다.
debounce 기능 구현 했고, nav바 기본 이미지, filter부분 focus하면 색상 남아있게끔 수정했습니다.

### ✨ To-do

- [x] '와인 등록하기' 버튼을 클릭하면 와인 등록 모달창을 띄우세요.
- [x] 전체 페이지 css 수정이 필요합니다.
- [ ] 태블릿, 모바일에서 사용할 필터 모달이 필요합니다.

### 📸 참고 사진
![Image](https://github.com/user-attachments/assets/d695479a-f22d-40e2-95fb-8595265cf140)
![Image](https://github.com/user-attachments/assets/1ecbe009-9c23-4c51-8ebe-1f3baa27595b)
![Image](https://github.com/user-attachments/assets/a906df11-dda0-4d18-8133-30db3bf9ddf6)
![Image](https://github.com/user-attachments/assets/89757b40-926c-47db-a4cc-54785f0e6797)
![Image](https://github.com/user-attachments/assets/427e16f6-8a39-4fe8-bb27-1776b5870871)
![Image](https://github.com/user-attachments/assets/0b4e2029-4582-4c03-9a61-75d5ad9b4cb0)
![Image](https://github.com/user-attachments/assets/c4aeb927-1f32-4a37-ba52-160e59ec20ab)
