### ISSUE TITLE
[ 전체 ] 수정 사항(최종 점검 이후 반영 필요)

### ISSUE THREAD

**Issue by KimLuka** [Sprint-11-5team/WHYNE#145]
### 📝 간단하게 설명해주세요

>

### ✨ To-do(Required)

- [ ] 모달 test 페이지 폴더 및 파일 삭제
- [ ] 이외에 폴더 및 파일 구조 점검 필요

### ✔️ To-do(Required?)
- [ ] 로그인 실패 시 이메일 초기화 -> 남겨놓기
![Image](https://github.com/user-attachments/assets/545a01e3-eff7-452f-b989-e8e49b6eabb6)
