### ISSUE TITLE
[ 회원가입 ] 간편 회원가입 UI

### ISSUE THREAD

**Issue by KimLuka** [Sprint-11-5team/WHYNE#16]
### 📝 간단하게 설명해주세요
> 구글 및 카카오톡을 통한 간편 회원가입 기능을 구현하세요

### ✨ To-do
- [ ] 간편 로그인 CSS
- [ ] 

- [ ] 로그인되면 홈 화면(`/`)으로 이동하세요. 
- [ ] 회원가입되지 않은 경우 `/oauth/signup/{google|kakao}`로 이동하세요.
- [ ] 에러 발생 시 에러 메시지를 띄워주세요. 

### 📸 참고 사진

**사진 변경되어야 함. 회원가입 디자인 제대로 없어서 임의로 로그인 페이지 캡쳐.**

<img width="323" alt="Image" src="https://github.com/user-attachments/assets/9a4ea00a-ad79-47e0-9521-164f08011f50" />
