### ISSUE TITLE
와인등록모달 반응형 수정

### ISSUE THREAD

**Issue by part3-5** [Sprint-11-5team/WHYNE#186]
### 📝 간단하게 설명해주세요

>

### ✨ To-do

- [x] 다른 테스트 페이지(비슷한 요소 복붙)에서 와인사진 업로드, 와인 등록 되는 것으로 확인
- [x] 모달 스크롤바 없앰
- [x]  와인 사진과 그 아래 gap 넣기
> - [x] IPhone SE버전에서는 갭이 2rem, 나머지는 3rem (se디바이스에서 상단여백을 주고 높이 맞추려면 갭2rem이 최대)<br><br>

### 📸 참고 사진<br><br>

모달 스크롤바 없앰<br>
![image](https://github.com/user-attachments/assets/fc76dbc0-db26-4ba4-ac43-77708e7dce51)<br><br><br>

갤럭시z폴드5,갤럭시s8+에서 와인페이지 반응형이 깨지네요<br>
![image](https://github.com/user-attachments/assets/1d32e9fb-835a-43c7-949d-a7e49efcef74)<br><br><br>

문제되는 디바이스에서도 모달 스크롤바 없습니다.<br>
![image](https://github.com/user-attachments/assets/c74e014e-7ee9-41ee-baa9-815b0ea9fa3d)<br><br><br>

가장 작은 디바이스 아이폰se에서 gap있습니다.<br>
![image](https://github.com/user-attachments/assets/4bb84ddf-b750-4749-ad80-f379baa4b16a)<br><br><br>

와인 페이지 문제
와인등록모달을 열기 전부터 와인페이지의 반응형이 깨지는
디바이스에서는 와인등록도 안됨 ex) 갤럭시z폴드5, 갤럭시s8+,태블릿
- 위를 제외한 모바일 디바이스에서는 와인등록 됨
- 전체 화면(데스크탑)에서 안됨

**비슷한 페이지로 따로 만들어서 실행해봤을 때에는**
**디바이스별로 와인등록(+와인사진) 됩니다.**
