### ISSUE TITLE
[ 기초세팅 ] Vercel 재배포

### ISSUE THREAD

**Issue by KimLuka** [Sprint-11-5team/WHYNE#19]
### 📝 간단하게 설명해주세요

> github organization 에서 Vercel 배포하면 개인 레포지토리 생성 - 팀 레포지토리를 여기에 올리고 개인 레포지토리를 배포하게 됨
> 그래서 개인 - 팀 레포지토리 연동하는 작업 따로 해야 함..vercel 에서 편하게 해주는 건 유료임
> https://velog.io/@rmaomina/organization-vercel-hobby-deploy

### ✨ To-do

- [ ] build.sh 파일 생성
- [ ] secret 변수 등록
- [ ] GitHub Actions 활성화 & 워크플로우 생성
