### ISSUE TITLE
[ / ] nav-component

### ISSUE THREAD

**Issue by lemon1335** [Sprint-11-5team/WHYNE#27]
### 📝 간단하게 설명해주세요

> 반응형 관련해서 tailwind.config.ts / global.css / next.config.ts 파일 수정되었습니다.
> 내일 pr올리고 승인되면 반응형 작업부분 관련해서 다시 말씀 드리겠습니다.

### ✨ To-do

- [x] 로고 버튼'을 클릭하면 새로고침하여 `/` 페이지로 이동하세요.
- [x] '로그인' 버튼을 클릭하면 `/login` 페이지로 이동하세요.
- [x] '회원가입' 버튼을 클릭하면 `/signup` 페이지로 이동하세요.

### 📸 참고 사진
![Image](https://github.com/user-attachments/assets/ba8e3886-fbb9-45c2-985f-51eed5985904)
