### ISSUE TITLE
[ /wines, /wines/{wineid}, /myprofile ] main-nav-component

### ISSUE THREAD

**Issue by lemon1335** [Sprint-11-5team/WHYNE#32]
### 📝 간단하게 설명해주세요

> 로그인 되어 있을 때 profile 이미지값을 받습니다.
> 로그인 되어있지 않을 때 로그인을 클릭하면 로그인 페이지로 넘어갑니다.

### ✨ To-do

- [ ] 로그인 되어 있을 때 profile 이미지값을 받습니다.
- [x] 로그인 상태일 때 profile 이미지를 클릭하면 마이페이지, 로그아웃 선택 버튼이 나타납니다.
- [x] 로그인 되어있지 않을 때 로그인을 클릭하면 로그인 페이지로 넘어갑니다.

### 📸 참고 사진
![Image](https://github.com/user-attachments/assets/43818fba-764a-4dba-b8ee-816fcb2de06d)
![Image](https://github.com/user-attachments/assets/917948a1-39d5-4920-86db-276fd966efc1)
