### ISSUE TITLE
[ 공용 ] 모달 컨테이너

### ISSUE THREAD

**Issue by part3-5** [Sprint-11-5team/WHYNE#48]
## 🪐 작업 내용
add moda-container 

### 📝 간단하게 설명해주세요

> 모달의 기본 틀을 제공하는 컴포넌트

공통 기능 재사용(내용물만 바꿔서)

### ✨ To-do

- [x] 열기 버튼 클릭시 모달창이 열린다.
- [x] 닫기 버튼 클릭시 창이 꺼진다.
- [x] 바깥쪽을 클릭시 창이 꺼진다.
- [x] 내부 클릭 시 모달창이 안 꺼진다.
