### ISSUE TITLE
test

### ISSUE THREAD

**Issue by part3-5** [Sprint-11-5team/WHYNE#5]
## 🛰️ Issue Number
ISSUE- 

	

### 📝 간단하게 설명해주세요
>

### ✨ To-do

- [ ] 정보를 입력한 후 '리뷰 남기기' 버튼을 클릭하면 리뷰가 등록되게 해주세요.

- [ ] 등록 후 모달창을 닫아주세요. 

- [ ] 'X' 버튼을 클릭하면 모달창을 닫아주세요.

- [ ] 별점, 후기, 와인의 맛과 향을 입력할 수 있게 해주세요.
