### ISSUE TITLE
test

### ISSUE THREAD

**Issue by part3-5** [Sprint-11-5team/WHYNE#6]
## 🛰️ Issue Number
ISSUE-

	

### 📝 간단하게 설명해주세요
>

### ✨ To-do

- [ ] 이름, 가격, 원산지, 사진, 타입을 입력할 수 있게 해주세요.

- [ ] 정보를 입력한 후 '와인 등록하기' 버튼을 클릭하면 와인이 등록되게 해주세요.

- [ ] 와인 등록 후 해당 와인의 상세 페이지로 이동하세요.

- [ ] - 'X' 버튼을 클릭하면 모달창을 닫아주세요.
