### ISSUE TITLE
[ /wines ] 목록페이지 ui 구현 1차

### ISSUE THREAD

**Issue by lemon1335** [Sprint-11-5team/WHYNE#78]
### 📝 간단하게 설명해주세요

> ui 먼저 빼놓고 데이터는 나중에 붙이겠습니다.

### ✨ To-do

- [x] types filter 컴포넌트
- [x] price filter 컴포넌트
- [x] rating filter 컴포넌트
- [ ] 상단 추천 와인 카드 컴포넌트
- [ ] 카드 리스트 컴포넌트
- [ ] 와인 카드를 클릭하면 해당 와인의 상세 페이지로 이동하세요.

### 📸 참고 사진
![Image](https://github.com/user-attachments/assets/63008014-c214-4d2a-a945-94959ded7ce2)
![Image](https://github.com/user-attachments/assets/ff7bc445-fa90-4d89-9d5b-3936c9a6df1d)
