### ISSUE TITLE
[ /wines ] 와인 목록 페이지 ui구현 2차

### ISSUE THREAD

**Issue by lemon1335** [Sprint-11-5team/WHYNE#79]
### 📝 간단하게 설명해주세요

> 어제 했던 ui 다듬고, 나머지 컴포넌트인 검색창, 카드, 카드리스트 ui 만들겠습니다.
> 생각보다 깔끔하게 안나와서 어떻게 해야할지... 고민입니다.
> 상세페이지는 id값이 필요해서 우선은 경로를 /wines로 설정했습니다.
> 텍스트와 이미지로 입혀두었어요.

### ✨ To-do
- [x] 상단 추천 와인 카드 컴포넌트
- [x] 카드 리스트 컴포넌트
- [ ] 와인 카드를 클릭하면 해당 와인의 상세 페이지로 이동하세요.
- [ ] 상단에 추천 와인을 랜덤으로 보여주세요.

### 📸 참고 사진
![Image](https://github.com/user-attachments/assets/02d0d541-5f53-4871-8eeb-d3bf6ee3b975)
![Image](https://github.com/user-attachments/assets/0e960e22-5ad4-47c3-aba9-0def003a2db1)
![Image](https://github.com/user-attachments/assets/1cbdf0f9-36c8-425d-bc1e-68999fc3ea78)
![Image](https://github.com/user-attachments/assets/80609a7e-8aa3-40d6-ae79-131f2198a8bc)
