### ISSUE TITLE
test

### ISSUE THREAD

**Issue by KimLuka** [Sprint-11-5team/WHYNE#8]
### 📝 간단하게 설명해주세요
> 회원가입 페이지에서 인풋창 기능을 추가합니다.
> 유효성 검사 -> 에러 메시지 출력

### ✨ To-do

- [ ] 이메일 입력창에서 blur될 때, 빈 값이면 “이메일은 필수 입력입니다.” 에러 메시지를 보여주세요.
- [ ] 이메일 형식이 아니면 “이메일 형식으로 작성해 주세요.” 에러 메시지를 보여주세요.
- [ ] 닉네임이 비어있으면 “닉네임은 필수 입력입니다.” 에러 메시지를 보여주세요.
- [ ] 닉네임이 20자를 초과하면 “닉네임은 최대 20자까지 가능합니다.” 에러 메시지를 보여주세요.
- [ ] 비밀번호가 비어있으면 “비밀번호는 필수 입력입니다.” 에러 메시지를 보여주세요.
- [ ] 비밀번호가 8자 미만이면 “비밀번호는 최소 8자 이상입니다.” 에러 메시지를 보여주세요.
- [ ] 비밀번호가 숫자, 영문, 특수문자(!@#$%^&*)만으로 이루어지지 않았다면 “비밀번호는 숫자, 영문, 특수문자로만 가능합니다.” 에러 메시지를 보여주세요.
- [ ] 비밀번호 확인 창에서 빈 값이면 “비밀번호 확인을 입력해주세요.” 에러 메시지를 보여주세요.
- [ ] 비밀번호와 비밀번호 확인이 일치하지 않으면 “비밀번호가 일치하지 않습니다.” 에러 메시지를 보여주세요.

<img width="854" alt="Image" src="https://github.com/user-attachments/assets/e1aa73e6-0243-4bd0-bda1-ffd21f382e7d" />
