### ISSUE TITLE
[ 회원가입 ] 고도화&리팩토링

### ISSUE THREAD

**Issue by KimLuka** [Sprint-11-5team/WHYNE#88]
### 📝 간단하게 설명해주세요

> 기능 고도화 및 css 수정

### ✨ To-do

- [ ] 이메일, 닉네임 서버에서 조회 -> 이미 있을 경우 alert / 에러 메시지
- [ ] [타입 가드](https://velog.io/@minseoook/axios-%EC%98%A4%EB%A5%98-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0isAxiosError%ED%83%80%EC%9E%85-%EA%B0%80%EB%93%9C-%ED%99%9C%EC%9A%A9)
- [ ] alert -> modal
- [ ] 유효성 검사 부분 zod 라이브러리 리팩토링(선택사항)
- [ ] 파일명 통일
- [x] 로그아웃 시 리프레시 토큰 초기화
