### ISSUE TITLE
test

### ISSUE THREAD

**Issue by KimLuka** [Sprint-11-5team/WHYNE#9]
### 📝 간단하게 설명해주세요
> 입력값 모두 정상인지 확인하고, 그전까지 disabled 등으로 버튼 비활성화 해놓음
> 모두 정상이면 엔터나 클릭 둘 다 버튼 submit 되게 하고
> 완료되면 data request, 반영 여부 확인
> navigate('/')로 홈 화면 이동

### ✨ To-do
- [ ] 입력값 모두 정상일 때 '가입하기' 버튼 활성화
- [ ] 클릭 / 엔터 누르면 회원가입 완료(데이터 정상 반영 확인)
- [ ] 로그인된 상태로 홈 화면(/) 이동

### 📸 참고 사진
<img width="1008" alt="Image" src="https://github.com/user-attachments/assets/f6368a02-e7bf-48db-b608-db1cdf45b490" />
