### ISSUE TITLE
[ /wines ] api 연동 1차, css수정

### ISSUE THREAD

**Issue by lemon1335** [Sprint-11-5team/WHYNE#90]
### 📝 간단하게 설명해주세요

> 상단에 추천 와인을 랜덤으로 보여주세요.
> 검색어 입력 후 '검색' 버튼을 클릭하거나 엔터를 누르면 검색 결과가 나타나게 해주세요.
> 와인 카드를 클릭하면 해당 와인의 상세 페이지로 이동하세요.
> 현재 전체 목록 데이터 조회 되는 상황이고, 별점순을 제외한 필터들은 정상적으로 작동하는 것으로 확인됩니다.
> 추천순은 리스트가 0보다 클 때 나오도록 해놓앗는데, 스웨거 조회해보면 1개가 조회가 되는 상황인데,, 0개일 때의 내용이 떠서.. 코드 상 문제인 것 같긴 한데 데이터 조금 더 넣어봐야 알 것 같아요..
> 별점 받은 %만큼 계산해서 보여주는 걸 아직 구현 못해서 혹시 아시는 분 계시다면 알려주세요~!

### ✨ To-do

- [ ] 상단에 추천 와인을 랜덤으로 보여주세요.
- [x] 검색어 입력 후 '검색' 버튼을 클릭하거나 엔터를 누르면 검색 결과가 나타나게 해주세요.
- [ ] 와인 카드를 클릭하면 해당 와인의 상세 페이지로 이동하세요.

### 📸 참고 사진
![Image](https://github.com/user-attachments/assets/86bb5b81-fcef-47b4-a199-91e59e050bb1)
![Image](https://github.com/user-attachments/assets/9fe1c5bd-8908-4c4f-940f-94c09b153f34)
![Image](https://github.com/user-attachments/assets/5cb672cd-48c4-4f67-af7e-388490159291)
![Image](https://github.com/user-attachments/assets/6c735fdf-0bc2-4a04-bf9c-36410d24e556)
